In [1]:
a = 5
b = 10
print(a + b)

15

In [45]:
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

yf.set_tz_cache_location("/Users/sou/EngineerSou/AlgoTrade/cache")

In [62]:
ticker=['SPY', 'AAPL', 'KO']
stocks = yf.download(ticker, start = '2022-01-01',end = '2022-01-30')
stocks

[*********************100%%**********************]  3 of 3 completed

             Adj Close                              Close             \
                  AAPL         KO         SPY        AAPL         KO
Date
2022-01-03  180.190964  56.279053  464.923370  182.009995  59.299999
2022-01-04  177.904053  57.218620  464.767670  179.699997  60.290001
2022-01-05  173.171814  57.693150  455.843109  174.919998  60.790001
2022-01-06  170.281021  57.389454  455.414886  172.000000  60.470001
2022-01-07  170.449295  57.256584  453.614380  172.169998  60.330002
2022-01-10  170.469101  57.351490  453.049957  172.190002  60.430000
2022-01-11  173.330246  57.370468  457.176453  175.080002  60.450001
2022-01-12  173.775742  57.455879  458.412415  175.529999  60.540001
2022-01-13  170.469101  57.797543  452.096191  172.190002  60.900002
2022-01-14  171.340332  58.262581  452.281067  173.070007  61.389999
2022-01-18  168.102997  57.797543  444.271362  169.800003  60.900002
2022-01-19  164.568680  57.892448  439.658234  166.229996  61.000000
2022-01-20  162.865875  57.655186  434.792053  164.509995  60.750000
2022-01-21  160.786850  57.370468  426.256805  162.410004  60.450001
2022-01-24  160.004730  56.905430  428.067078  161.619995  59.959999
2022-01-25  158.183151  56.772564  422.840759  159.779999  59.820000
2022-01-26  158.094055  56.563766  421.779968  159.690002  59.599998
2022-01-27  157.628738  56.611221  419.697205  159.220001  59.650002
2022-01-28  168.627701  57.740601  430.120575  170.330002  60.840000

                              High                                Low  \
                   SPY        AAPL         KO         SPY        AAPL
Date
2022-01-03  477.709991  182.880005  59.310001  477.850006  177.710007
2022-01-04  477.549988  182.940002  60.540001  479.980011  179.119995
2022-01-05  468.380005  180.169998  61.200001  477.980011  174.639999
2022-01-06  467.940002  175.300003  61.119999  470.820007  171.639999
2022-01-07  466.089996  174.139999  60.720001  469.200012  171.029999
2022-01-10  465.510010  172.500000  60.820000  465.739990  168.169998
2022-01-11  469.750000  175.179993  60.490002  469.850006  170.820007
2022-01-12  471.019989  177.179993  60.689999  473.200012  174.820007
2022-01-13  464.529999  176.619995  61.040001  472.880005  171.789993
2022-01-14  464.720001  173.779999  61.450001  465.089996  171.089996
2022-01-18  456.489990  172.539993  61.189999  459.959991  169.410004
2022-01-19  451.750000  171.080002  61.180000  459.609985  165.940002
2022-01-20  446.750000  169.679993  61.439999  458.739990  164.179993
2022-01-21  437.980011  166.330002  61.299999  448.059998  162.300003
2022-01-24  439.839996  162.300003  60.349998  440.380005  154.699997
2022-01-25  434.470001  162.759995  60.049999  439.720001  157.020004
2022-01-26  433.380005  164.389999  60.349998  444.040009  157.820007
2022-01-27  431.239990  163.839996  60.930000  441.589996  158.279999
2022-01-28  441.950012  170.350006  60.889999  442.000000  162.800003

                                         Open                         \
                   KO         SPY        AAPL         KO         SPY
Date
2022-01-03  58.380001  473.850006  177.830002  58.820000  476.299988
2022-01-04  59.590000  475.579987  182.630005  59.730000  479.220001
2022-01-05  60.049999  468.279999  179.610001  60.090000  477.160004
2022-01-06  60.439999  465.429993  172.699997  60.470001  467.890015
2022-01-07  60.060001  464.649994  172.889999  60.279999  467.950012
2022-01-10  60.180000  456.600006  169.080002  60.549999  462.700012
2022-01-11  59.840000  462.049988  172.320007  60.430000  465.230011
2022-01-12  60.189999  468.940002  176.119995  60.529999  471.589996
2022-01-13  60.389999  463.440002  175.779999  60.540001  472.190002
2022-01-14  60.360001  459.899994  171.339996  60.939999  461.190002
2022-01-18  60.450001  455.309998  171.509995  61.060001  459.739990
2022-01-19  60.560001  451.459991  170.000000  60.660000  458.130005
2022-01-20  60.720001  444.500000  166.979996  61.000000  453.750000
2022-01-21  60.400002  437.950012  164.419998  61.080002  445.559998
2022-01-24  58.570000  420.760010  160.020004  59.900002  432.029999
2022-01-25  58.689999  427.149994  158.979996  59.360001  433.059998
2022-01-26  59.209999  428.859985  163.500000  59.790001  440.720001
2022-01-27  59.500000  429.450012  162.449997  59.880001  438.260010
2022-01-28  58.939999  427.820007  165.710007  59.389999  432.679993

               Volume
                 AAPL        KO        SPY
Date
2022-01-03  104487900  20187300   72668200
2022-01-04   99310400  26141600   71178700
2022-01-05   94537600  22507300  104538900
2022-01-06   96904000  17902300   86858900
2022-01-07   86709100  12307900   85111600
2022-01-10  106765600  20954300  119362000
2022-01-11   76138300  19369600   74303100
2022-01-12   74805200  15753800   67605400
2022-01-13   84505800  14318000   91173100
2022-01-14   80440800  19729600   95890900
2022-01-18   90956700  21976700  109709100
2022-01-19   94815000  18654700  109357600
2022-01-20   91420500  23002400  122379700
2022-01-21  122848900  26643200  202271200
2022-01-24  162294600  30185100  251783900
2022-01-25  115798400  19027100  167997300
2022-01-26  108275300  19190200  186391100
2022-01-27  121954600  18893800  149878300
2022-01-28  179935700  19101500  164457400

In [64]:
stocks.to_csv('souPicks.csv', index=False)
stocks

             Adj Close                              Close             \
                  AAPL         KO         SPY        AAPL         KO
Date
2022-01-03  180.190964  56.279053  464.923370  182.009995  59.299999
2022-01-04  177.904053  57.218620  464.767670  179.699997  60.290001
2022-01-05  173.171814  57.693150  455.843109  174.919998  60.790001
2022-01-06  170.281021  57.389454  455.414886  172.000000  60.470001
2022-01-07  170.449295  57.256584  453.614380  172.169998  60.330002
2022-01-10  170.469101  57.351490  453.049957  172.190002  60.430000
2022-01-11  173.330246  57.370468  457.176453  175.080002  60.450001
2022-01-12  173.775742  57.455879  458.412415  175.529999  60.540001
2022-01-13  170.469101  57.797543  452.096191  172.190002  60.900002
2022-01-14  171.340332  58.262581  452.281067  173.070007  61.389999
2022-01-18  168.102997  57.797543  444.271362  169.800003  60.900002
2022-01-19  164.568680  57.892448  439.658234  166.229996  61.000000
2022-01-20  162.865875  57.655186  434.792053  164.509995  60.750000
2022-01-21  160.786850  57.370468  426.256805  162.410004  60.450001
2022-01-24  160.004730  56.905430  428.067078  161.619995  59.959999
2022-01-25  158.183151  56.772564  422.840759  159.779999  59.820000
2022-01-26  158.094055  56.563766  421.779968  159.690002  59.599998
2022-01-27  157.628738  56.611221  419.697205  159.220001  59.650002
2022-01-28  168.627701  57.740601  430.120575  170.330002  60.840000

                              High                                Low  \
                   SPY        AAPL         KO         SPY        AAPL
Date
2022-01-03  477.709991  182.880005  59.310001  477.850006  177.710007
2022-01-04  477.549988  182.940002  60.540001  479.980011  179.119995
2022-01-05  468.380005  180.169998  61.200001  477.980011  174.639999
2022-01-06  467.940002  175.300003  61.119999  470.820007  171.639999
2022-01-07  466.089996  174.139999  60.720001  469.200012  171.029999
2022-01-10  465.510010  172.500000  60.820000  465.739990  168.169998
2022-01-11  469.750000  175.179993  60.490002  469.850006  170.820007
2022-01-12  471.019989  177.179993  60.689999  473.200012  174.820007
2022-01-13  464.529999  176.619995  61.040001  472.880005  171.789993
2022-01-14  464.720001  173.779999  61.450001  465.089996  171.089996
2022-01-18  456.489990  172.539993  61.189999  459.959991  169.410004
2022-01-19  451.750000  171.080002  61.180000  459.609985  165.940002
2022-01-20  446.750000  169.679993  61.439999  458.739990  164.179993
2022-01-21  437.980011  166.330002  61.299999  448.059998  162.300003
2022-01-24  439.839996  162.300003  60.349998  440.380005  154.699997
2022-01-25  434.470001  162.759995  60.049999  439.720001  157.020004
2022-01-26  433.380005  164.389999  60.349998  444.040009  157.820007
2022-01-27  431.239990  163.839996  60.930000  441.589996  158.279999
2022-01-28  441.950012  170.350006  60.889999  442.000000  162.800003

                                         Open                         \
                   KO         SPY        AAPL         KO         SPY
Date
2022-01-03  58.380001  473.850006  177.830002  58.820000  476.299988
2022-01-04  59.590000  475.579987  182.630005  59.730000  479.220001
2022-01-05  60.049999  468.279999  179.610001  60.090000  477.160004
2022-01-06  60.439999  465.429993  172.699997  60.470001  467.890015
2022-01-07  60.060001  464.649994  172.889999  60.279999  467.950012
2022-01-10  60.180000  456.600006  169.080002  60.549999  462.700012
2022-01-11  59.840000  462.049988  172.320007  60.430000  465.230011
2022-01-12  60.189999  468.940002  176.119995  60.529999  471.589996
2022-01-13  60.389999  463.440002  175.779999  60.540001  472.190002
2022-01-14  60.360001  459.899994  171.339996  60.939999  461.190002
2022-01-18  60.450001  455.309998  171.509995  61.060001  459.739990
2022-01-19  60.560001  451.459991  170.000000  60.660000  458.130005
2022-01-20  60.720001  444.500000  166.979996  61.000000  453.750000
2022-01-21  60.400002  437.950012  164.419998  61.080002  445.559998
2022-01-24  58.570000  420.760010  160.020004  59.900002  432.029999
2022-01-25  58.689999  427.149994  158.979996  59.360001  433.059998
2022-01-26  59.209999  428.859985  163.500000  59.790001  440.720001
2022-01-27  59.500000  429.450012  162.449997  59.880001  438.260010
2022-01-28  58.939999  427.820007  165.710007  59.389999  432.679993

               Volume
                 AAPL        KO        SPY
Date
2022-01-03  104487900  20187300   72668200
2022-01-04   99310400  26141600   71178700
2022-01-05   94537600  22507300  104538900
2022-01-06   96904000  17902300   86858900
2022-01-07   86709100  12307900   85111600
2022-01-10  106765600  20954300  119362000
2022-01-11   76138300  19369600   74303100
2022-01-12   74805200  15753800   67605400
2022-01-13   84505800  14318000   91173100
2022-01-14   80440800  19729600   95890900
2022-01-18   90956700  21976700  109709100
2022-01-19   94815000  18654700  109357600
2022-01-20   91420500  23002400  122379700
2022-01-21  122848900  26643200  202271200
2022-01-24  162294600  30185100  251783900
2022-01-25  115798400  19027100  167997300
2022-01-26  108275300  19190200  186391100
2022-01-27  121954600  18893800  149878300
2022-01-28  179935700  19101500  164457400

In [65]:
stocks = pd.read_csv('souPicks.csv')
stocks

,Adj Close,Adj Close.1,Adj Close.2,Close,Close.1,Close.2,High,High.1,High.2,Low,Low.1,Low.2,Open,Open.1,Open.2,Volume,Volume.1,Volume.2
0,AAPL,KO,SPY,AAPL,KO,SPY,AAPL,KO,SPY,AAPL,KO,SPY,AAPL,KO,SPY,AAPL,KO,SPY
1,180.1909637451172,56.279052734375,464.9233703613281,182.00999450683594,59.29999923706055,477.7099914550781,182.8800048828125,59.310001373291016,477.8500061035156,177.7100067138672,58.380001068115234,473.8500061035156,177.8300018310547,58.81999969482422,476.29998779296875,104487900,20187300,72668200
2,177.904052734375,57.21862030029297,464.7676696777344,179.6999969482422,60.290000915527344,477.54998779296875,182.94000244140625,60.540000915527344,479.9800109863281,179.1199951171875,59.59000015258789,475.5799865722656,182.6300048828125,59.72999954223633,479.2200012207031,99310400,26141600,71178700
3,173.17181396484375,57.69314956665039,455.8431091308594,174.9199981689453,60.790000915527344,468.3800048828125,180.1699981689453,61.20000076293945,477.9800109863281,174.63999938964844,60.04999923706055,468.2799987792969,179.61000061035156,60.09000015258789,477.1600036621094,94537600,22507300,104538900
4,170.28102111816406,57.38945388793945,455.4148864746094,172.0,60.470001220703125,467.94000244140625,175.3000030517578,61.119998931884766,470.82000732421875,171.63999938964844,60.439998626708984,465.42999267578125,172.6999969482422,60.470001220703125,467.8900146484375,96904000,17902300,86858900
5,170.4492950439453,57.25658416748047,453.6143798828125,172.1699981689453,60.33000183105469,466.0899963378906,174.13999938964844,60.720001220703125,469.20001220703125,171.02999877929688,60.060001373291016,464.6499938964844,172.88999938964844,60.279998779296875,467.95001220703125,86709100,12307900,85111600
6,170.46910095214844,57.35149002075195,453.0499572753906,172.19000244140625,60.43000030517578,465.510009765625,172.5,60.81999969482422,465.739990234375,168.1699981689453,60.18000030517578,456.6000061035156,169.0800018310547,60.54999923706055,462.70001220703125,106765600,20954300,119362000
7,173.3302459716797,57.37046813964844,457.17645263671875,175.0800018310547,60.45000076293945,469.75,175.17999267578125,60.4900016784668,469.8500061035156,170.82000732421875,59.84000015258789,462.04998779296875,172.32000732421875,60.43000030517578,465.2300109863281,76138300,19369600,74303100
8,173.77574157714844,57.45587921142578,458.41241455078125,175.52999877929688,60.540000915527344,471.0199890136719,177.17999267578125,60.689998626708984,473.20001220703125,174.82000732421875,60.189998626708984,468.94000244140625,176.1199951171875,60.529998779296875,471.5899963378906,74805200,15753800,67605400
9,170.46910095214844,57.797542572021484,452.09619140625,172.19000244140625,60.900001525878906,464.5299987792969,176.6199951171875,61.040000915527344,472.8800048828125,171.7899932861328,60.38999938964844,463.44000244140625,175.77999877929688,60.540000915527344,472.19000244140625,84505800,14318000,91173100
10,171.34033203125,58.26258087158203,452.28106689453125,173.07000732421875,61.38999938964844,464.7200012207031,173.77999877929688,61.45000076293945,465.0899963378906,171.08999633789062,60.36000061035156,459.8999938964844,171.33999633789062,60.939998626708984,461.19000244140625,80440800,19729600,95890900
11,168.10299682617188,57.797542572021484,444.2713623046875,169.8000030517578,60.900001525878906,456.489990234375,172.5399932861328,61.189998626708984,459.9599914550781,169.41000366210938,60.45000076293945,455.30999755859375,171.50999450683594,61.060001373291016,459.739990234375,90956700,21976700,109709100
12,164.5686798095703,57.89244842529297,439.6582336425781,166.22999572753906,61.0,451.75,171.0800018310547,61.18000030517578,459.6099853515625,165.94000244140625,60.560001373291016,451.4599914550781,170.0,60.65999984741211,458.1300048828125,94815000,18654700,109357600
13,162.86587524414062,57.65518569946289,434.79205322265625,164.50999450683594,60.75,446.75,169.67999267578125,61.439998626708984,458.739990234375,164.17999267578125,60.720001220703125,444.5,166.97999572753906,61.0,453.75,91420500,23002400,122379700
14,160.78684997558594,57.37046813964844,426.2568054199219,162.41000366210938,60.45000076293945,437.9800109863281,166.3300018310547,61.29999923706055,448.05999755859375,162.3000030517578,60.400001525878906,437.95001220703125,164.4199981689453,61.08000183105469,445.55999755859375,122848900,26643200,202271200
15,160.00473022460938,56.90542984008789,428.06707763671875,161.6199951171875,59.959999084472656,439.8399963378906,162.3000030517578,60.349998474121094,440.3800048828125,154.6999969482422,58.56999969482422,420.760009765625,160.02000427246094,59.900001525878906,432.0299987792969,162294600,30185100,251783900
16,158.1831512451172,56.77256393432617,422.84075927734375,159.77999877929688,59.81999969482422,434.4700012207031,162.75999450683594,60.04999923706055,439.7200012207031,157.02000427246094,58.689998626708984,427.1499938964844,158.97999572753906,59.36000061035156,433.05999755859375,115798400,19027100,167997300
17,158.09405517578125,56.56376647949219,421.77996826171875,159.69000244140625,59.599998474121094,433.3800048828125,164.38999938964844,60.349998474121094,444.0400085449219,157.82000732421875,59.209999084472656,428.8599853515625,163.5,59.790000915527344,440.7200012207031,108275300,19190200,186391100
18,157.6287384033203,56.61122131347656,419.69720458984375,159.22000122070312,59.650001525878906,431.239990234375,163.83999633789062,60.93000030517578,441.5899963378906,158.27999877929688,59.5,429.45001220703125,162.4499969482422,59.880001068115234,438.260009765625,121954600,18893800,149878300
19,168.62770080566406,57.7406005859375,430.1205749511719,170.3300018310547,60.84000015258789,441.95001220703125,170.35000610351562,60.88999938964844,442.0,162.8000030517578,58.939998626708984,427.82000732421875,165.7100067138672,59.38999938964844,432.67999267578125,179935700,19101500,164457400

In [38]:
# Create a Tickers object for multiple tickers
tickers = yf.Tickers('msft aapl goog')

# Create a dictionary to store the info of each ticker
info_dict = {}


for ticker in tickers.tickers:
    info_dict[ticker] = tickers.tickers[ticker].info

# Convert the dictionary to a DataFrame
info_df = pd.DataFrame.from_dict(info_dict, orient='index')

# Display the DataFrame
info_df

,address1,city,state,zip,country,phone,website,industry,industryKey,industryDisp,...,freeCashflow,operatingCashflow,earningsGrowth,revenueGrowth,grossMargins,ebitdaMargins,operatingMargins,financialCurrency,trailingPegRatio,grossProfits
MSFT,One Microsoft Way,Redmond,WA,98052-6399,United States,425 882 8080,https://www.microsoft.com,Software - Infrastructure,software-infrastructure,Software - Infrastructure,...,50418876416,94966996992,0.272,0.128,0.69441,0.49714,0.47587,USD,2.3187,NaN
AAPL,One Apple Park Way,Cupertino,CA,95014,United States,408 996 1010,https://www.apple.com,Consumer Electronics,consumer-electronics,Consumer Electronics,...,90680500224,113071996928,0.050,-0.014,0.43449,0.32286,0.28116,USD,2.1778,1.707820e+11
GOOG,1600 Amphitheatre Parkway,Mountain View,CA,94043,United States,650 253 0000,https://www.abc.xyz,Internet Content & Information,internet-content-information,Internet Content & Information,...,71757127680,106444996608,0.460,0.110,0.56122,0.32333,0.27962,USD,1.1620,1.566330e+11

In [39]:
#optional
msft_info = tickers.tickers['MSFT'].info
df_msft = pd.DataFrame.from_dict(msft_info, orient='index', columns=['MSFT'])
df_msft

                                MSFT
address1           One Microsoft Way
city                         Redmond
state                             WA
zip                       98052-6399
country                United States
...                              ...
grossMargins                 0.69441
ebitdaMargins                0.49714
operatingMargins             0.47587
financialCurrency                USD
trailingPegRatio              2.3187

[131 rows x 1 columns]

In [43]:
tickers.tickers['GOOG'].actions

                           Dividends  Stock Splits
Date
2014-03-27 00:00:00-04:00        0.0      2.002000
2015-04-27 00:00:00-04:00        0.0      1.002746
2022-07-18 00:00:00-04:00        0.0     20.000000

In [69]:
stocks.describe()

,Adj Close,Adj Close.1,Adj Close.2,Close,Close.1,Close.2,High,High.1,High.2,Low,Low.1,Low.2,Open,Open.1,Open.2,Volume,Volume.1,Volume.2
count,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20
unique,19,18,20,19,18,20,20,19,20,20,20,20,20,20,20,20,20,20
top,170.46910095214844,57.797542572021484,SPY,172.19000244140625,60.900001525878906,SPY,AAPL,60.349998474121094,SPY,AAPL,KO,SPY,AAPL,KO,SPY,AAPL,KO,SPY
freq,2,2,1,2,2,1,1,2,1,1,1,1,1,1,1,1,1,1

In [70]:
stocks.loc[:,"Close"]

0                   AAPL
1     182.00999450683594
2      179.6999969482422
3      174.9199981689453
4                  172.0
5      172.1699981689453
6     172.19000244140625
7      175.0800018310547
8     175.52999877929688
9     172.19000244140625
10    173.07000732421875
11     169.8000030517578
12    166.22999572753906
13    164.50999450683594
14    162.41000366210938
15     161.6199951171875
16    159.77999877929688
17    159.69000244140625
18    159.22000122070312
19     170.3300018310547
Name: Close, dtype: object

In [66]:
%matplotlib inline
plt.style.use('ggplot')

In [67]:
close.plot(figsize=(15,8), fontsize=12)

NameError: name 'close' is not defined